=== hcssmith/xmlwebsite/page.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="include">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="type" use="optional"/>
          <xs:attribute type="xs:string" name="url" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="menuitem">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="type" use="optional"/>
          <xs:attribute type="xs:string" name="destination" use="optional"/>
          <xs:attribute type="xs:string" name="text" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="menu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="menuitem" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="body_title" type="xs:string" />
  <xs:element name="subtitle" type="xs:string" />
  <xs:element name="para">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="footnote" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="url" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="footnote">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="id" />
          <xs:attribute name="description" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="text">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:sequence>
          <xs:element ref="para" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="para" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element ref="para" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="para" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="body_title" minOccurs="0"/>
        <xs:element ref="subtitle" minOccurs="0"/>
        <xs:element ref="text" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="includes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="include" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="menu"/>
        <xs:element ref="body"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="includes"/>
        <xs:element ref="content"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="title"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hcssmith/xmlwebsite/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>

<page title="hcssmith.com" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="./page.xsd">
  <includes>
    <include type="css" url="awsm.min.css" />
  </includes>
  <content>
    <menu>
      <menuitem type="link" destination="/" text="Home"/>
      <menuitem type="link" destination="/blog" text="Blog"/>
      <menuitem type="link" destination="/git" text="Git"/>
      <menuitem type="link" destination="/contact" text="Contact"/>
    </menu>
    <body>
      <subtitle>A repository for any projects and notes on technologies that I create</subtitle>
      <text>
        <image url="https://picsum.photos/seed/picsum/850/300" />
        <para>
          This site is build using XML and XSLT as an expermient. It is inteneded to have the xml files built by combining
          various differnet files at request time. I will be looking into some form of caching to only regen if the input 
          files are editied. and have things like includes (css) and menu (navbar) are definied in seaprate file. 
        </para>
      </text>
    </body>
  </content>
</page>

=== hcssmith/xmlwebsite/blog/20221126.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/xslt/page.xsl"?>

<page title="hcssmith.com" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="../schema/page.xsd">
  <includes>
    <include type="css" url="/awsm.min.css" />
  </includes>
  <content>
    <menu>
      <menuitem type="link" destination="/" text="Home"/>
      <menuitem type="link" destination="/blog" text="Blog"/>
      <menuitem type="link" destination="/project" text="Projects"/>
      <menuitem type="link" destination="https://github.com/hcssmith" text="Git"/>
      <menuitem type="link" destination="/contact" text="Contact"/>
    </menu>
    <body>
      <body_title>Notes on xslt</body_title>
      <subtitle>My collection of notes on xslt, helpful snippets and ideas for the future</subtitle>
      <text>
        <image url="https://picsum.photos/seed/picsum/850/300" />
        <para>
          This site is build using XML and XSLT as an expermient. It is inteneded to have the xml files built by combining
          various differnet files at request time. I will be looking into some form of caching to only regen if the input 
          files are editied. and have things like includes (css) and menu (navbar) are definied in seaprate file. 
        </para>
        <para>Lorem ipsum dolor sit amet, officia excepteur<footnote id="hsc" description="Something important" /> ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</para>
        <para>Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</para>
        <para>Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</para>
        <para>Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</para>
        <para>Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</para>
      </text>
    </body>
  </content>
</page>
